POST http://{{host}}/api/v1/accounts
Content-Type: application/json

{
  "customerId": "156f6516-33e3-41b6-9335-bbbff54d9098",
  "balance": {
    "currency":"USD",
    "amount":7000
  }
}
###
GET http://{{host}}/api/v1/accounts/156f6516-33e3-41b6-9335-abcff54d7000
Content-Type: application/json

###

POST http://{{host}}/api/v1/accounts/{account_id}/transfer
Content-Type: application/json

{
  "destinationId": "156f6516-33e3-41b6-9335-abcff54d7001",
  "amount": 100
}

###
