version: '3.1'
services:
  money-transfer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://money-transfer-db:54321/payment
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - money-transfer-db
      - exchange-service

  money-transfer-db:
    image: postgres:10.5
    restart: always
    ports:
      - "54321:54321"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment

  exchange-service:
    image: sandokandias/stubby4j-docker
    ports:
      - "8882:8882"
    environment:
      STUBBY_PORT: 8882
    volumes:
      - ./stubs/stubby.yml:/usr/local/stubby.yml

